# Generated by Django 5.2.4 on 2025-09-15 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeverified",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("00d6a5ee-d02e-4862-871e-5d6b62bdd463"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("00d6a5ee-d02e-4862-871e-5d6b62bdd463"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
