# Generated by Django 5.2.4 on 2025-09-05 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeverified",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6e703412-af53-4d91-aa6f-bee7d87125fd"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6e703412-af53-4d91-aa6f-bee7d87125fd"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
