# Generated by Django 5.2.4 on 2025-09-05 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_codeverified_id_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeverified",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("04bf4d5c-ad5b-48d3-a600-ca3bceb8061b"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("04bf4d5c-ad5b-48d3-a600-ca3bceb8061b"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
